//
//  SearchWorkerTests.swift
//  GiphySearch
//
//  Created by Collie on 2022/06/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GiphySearch
import XCTest

class SearchWorkerTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: SearchWorker!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupSearchWorker()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupSearchWorker() {
    sut = SearchWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
}
