//
//  DetailModels.swift
//  GiphySearch
//
//  Created by Collie on 2022/06/30.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Use cases
    enum Fetch {
        
        struct Request {
        }
        
        struct Response {
            var gif: Gif
            var isFavorite: Bool
        }
        
        struct ViewModel {
            var gif: Gif
            var isFavorite: Bool
        }
    }
    
    enum Update {
        struct Request {
            
        }
        
        struct Response {
            var isFavorite: Bool
        }
        
        struct ViewModel {
            var isFavorite: Bool
        }
    }
}
