//
//  DetailPresenter.swift
//  GiphySearch
//
//  Created by Collie on 2022/06/30.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentFetch(response: Detail.Fetch.Response)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
    
    func presentFetch(response: Detail.Fetch.Response) {
        let viewModel = Detail.Fetch.ViewModel(gif: response.gif)
        viewController?.displayFetch(viewModel: viewModel)
    }
}
