//
//  DetailWorker.swift
//  GiphySearch
//
//  Created by Collie on 2022/06/30.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker {
    func fetch(_ gif: Gif, completion: @escaping (Detail.Fetch.Response) -> Void) {
        let response = Detail.Fetch.Response(gif: gif, isFavorite: FavoriteManager.shared.list.contains(gif))
        completion(response)
    }
    
    func update(_ gif: Gif, isFavorite: Bool, completion: @escaping (Detail.Update.Response) -> Void) {
        isFavorite ? FavoriteManager.shared.create(gif) : FavoriteManager.shared.delete(gif)
        let response = Detail.Update.Response(isFavorite: isFavorite)
        completion(response)
    }
}
