//
//  FavoriteWorker.swift
//  GiphySearch
//
//  Created by Collie on 2022/07/01.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FavoriteWorker {
    func fetch(_ completion: @escaping (Favorite.Fetch.Response) -> Void) {
        let response = Favorite.Fetch.Response(list: FavoriteManager.shared.list)
        completion(response)
    }
}
