//
//  FavoritePresenter.swift
//  GiphySearch
//
//  Created by Collie on 2022/07/01.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritePresentationLogic {
    func presentFetch(response: Favorite.Fetch.Response)
}

class FavoritePresenter: FavoritePresentationLogic {
    weak var viewController: FavoriteDisplayLogic?
    
    func presentFetch(response: Favorite.Fetch.Response) {
        let viewModel = Favorite.Fetch.ViewModel(list: response.list)
        viewController?.displayFetch(viewModel: viewModel)
    }
}
