//
//  FavoriteRouter.swift
//  GiphySearch
//
//  Created by Collie on 2022/07/01.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoriteRoutingLogic {
    func routeToDetail()
}

protocol FavoriteDataPassing {
    var dataStore: FavoriteDataStore? { get }
}

class FavoriteRouter: NSObject, FavoriteRoutingLogic, FavoriteDataPassing {
    weak var viewController: FavoriteViewController?
    var dataStore: FavoriteDataStore?
    
    // MARK: Routing
    
    /*func routeToSomewhere(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! SomewhereViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }*/
    func routeToDetail() {
        let storyboard = UIStoryboard(name: "Detail", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: Navigation
    
    func navigateToDetail(source: FavoriteViewController, destination: DetailViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetail(source: FavoriteDataStore, destination: inout DetailDataStore) {
        guard let row = viewController!.collectionView.indexPathsForSelectedItems?.first?.row else { return }
        destination.gif = source.list[row]
    }
}
