//
//  SearchPresenter.swift
//  GiphySearch
//
//  Created by Collie on 2022/06/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentLoading()
    func presentTrending(response: Search.Trending.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    func presentLoading() {
        viewController?.displayLoading()
    }
    
    func presentTrending(response: Search.Trending.Response) {
        if let error = response.error {
            viewController?.displayError(error)
            return
        }
        
        let viewModel = Search.Trending.ViewModel(gif: response.gifs, totalCount: response.pagination?.totalCount ?? 0)
        viewController?.displayTrending(viewModel: viewModel)
    }
}
