//
//  SearchWorker.swift
//  GiphySearch
//
//  Created by Collie on 2022/06/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire

class SearchWorker {
    func trending(offset: Int, completion: @escaping (Search.Trending.Response) -> Void) {
        AF.request(GiphyAPI.trending(offset: offset))
            .validate()
            .responseDecodable(of: GifsResponse.self) { response in
                switch response.result {
                case let .success(value):
                    let response = Search.Trending.Response(gifs: value.data, pagination: value.pagination)
                    completion(response)
                    
                case let .failure(error):
                    let response = Search.Trending.Response(error: error)
                    completion(response)
                }
            }
    }
    
    func search(query: String, offset: Int, completion: @escaping (Search.Search.Response) -> Void) {
        
    }
}
